manifest:
  defaults:
    revision: v0.3
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: Good-Great-Grand-Wonderful
    url-base: https://github.com/Good-Great-Grand-Wonderful
  projects:
  - name: zmk
    remote: zmkfirmware
    import: app/west.yml
  - name: crosses-36-zmk-template
    url: https://github.com/Good-Great-Grand-Wonderful/crosses-36-zmk-template
    revision: main
    path: modules/crosses-36-zmk-template
  - name: gggw-zmk-keebs
    remote: Good-Great-Grand-Wonderful
    revision: main
    import: config/west.yml
  self:
    path: config
